controllers:
    resource: ../../src/Controller
    type: attribute
    prefix: /v1


when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error
